# Generated by Django 5.1.1 on 2024-09-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplication',
            name='efficacy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
