# Generated by Django 5.1.1 on 2024-09-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf_interface', '0002_webapplication_efficacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='webapplication',
            name='path',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
    ]
