# Generated by Django 5.1.1 on 2024-09-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf_interface', '0003_webapplication_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webapplication',
            old_name='efficacy',
            new_name='accuracy',
        ),
        migrations.AddField(
            model_name='webapplication',
            name='allowed_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='denied_percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='false_negative_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='false_positive_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='total_anomalous_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='total_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='total_valid_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='true_negative_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webapplication',
            name='true_positive_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
