# Generated by Django 5.1.1 on 2024-10-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('waf_details_path', models.CharField(max_length=200)),
                ('start_waf_path', models.CharField(max_length=200)),
                ('waf_address', models.CharField(max_length=200)),
                ('start_web_app_path', models.CharField(max_length=200)),
                ('web_app_address', models.CharField(max_length=200)),
                ('total_requests', models.IntegerField()),
                ('allowed_requests', models.IntegerField()),
                ('blocked_requests', models.IntegerField()),
                ('threats_detected', models.IntegerField()),
            ],
        ),
    ]
