# Generated by Django 5.1.1 on 2024-10-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waf',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
