# Generated by Django 5.1.1 on 2024-10-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0002_waf_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='waf',
            name='app_container_image_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='waf',
            name='app_container_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='waf',
            name='app_port_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waf',
            name='waf_container_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='waf',
            name='allowed_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waf',
            name='app_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='waf',
            name='blocked_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waf',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='waf',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='waf',
            name='total_requests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waf',
            name='waf_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
