# Generated by Django 5.1.1 on 2024-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0002_waf_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waf',
            old_name='start_waf_path',
            new_name='app_address',
        ),
        migrations.RenameField(
            model_name='waf',
            old_name='enabled',
            new_name='app_enabled',
        ),
        migrations.RemoveField(
            model_name='waf',
            name='start_web_app_path',
        ),
        migrations.RemoveField(
            model_name='waf',
            name='waf_details_path',
        ),
        migrations.RemoveField(
            model_name='waf',
            name='web_app_address',
        ),
        migrations.AddField(
            model_name='waf',
            name='waf_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
