# Generated by Django 5.1.1 on 2024-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0003_waf_app_container_image_name_waf_app_container_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waf',
            old_name='app_port_number',
            new_name='app_internal_port_number',
        ),
        migrations.AddField(
            model_name='waf',
            name='app_external_port_number',
            field=models.IntegerField(default=0),
        ),
    ]
