# Generated by Django 5.1.1 on 2024-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0004_rename_app_port_number_waf_app_internal_port_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waf',
            name='average_time',
            field=models.FloatField(default=0),
        ),
    ]
