# Generated by Django 5.1.1 on 2024-11-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0005_waf_average_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waf',
            old_name='average_time',
            new_name='total_time',
        ),
    ]
